// Code generated by tron1.0.0. DO NOT EDIT.

package suggest

import (
	context "context"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	transport "github.com/loghole/tron/transport"
	grpc "google.golang.org/grpc"
)

// SuggestServiceDesc is description for the SuggestServer.
type SuggestServiceDesc struct {
	svc SuggestServer
}

func NewSuggestServiceDesc(i SuggestServer) transport.ServiceDesc {
	return &SuggestServiceDesc{svc: i}
}

func (d *SuggestServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterSuggestServer(s, d.svc)
}

func (d *SuggestServiceDesc) RegisterHTTP(mux *runtime.ServeMux) {
	RegisterSuggestHandlerServer(context.Background(), mux, d.svc)
}

func (d *SuggestServiceDesc) SwaggerDef() []byte {
	return []byte(`{
  "swagger": "2.0",
  "info": {
    "title": "suggest.proto",
    "version": "version not set"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/v1/suggest/{type}": {
      "post": {
        "operationId": "Suggest_List",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/suggest.v1.ListResp"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/google.rpc.Status"
            }
          }
        },
        "parameters": [
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/suggest.v1.ListReq"
            }
          }
        ],
        "tags": [
          "Suggest"
        ]
      }
    }
  },
  "definitions": {
    "google.protobuf.Any": {
      "type": "object",
      "properties": {
        "typeUrl": {
          "type": "string"
        },
        "value": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "google.rpc.Status": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/google.protobuf.Any"
          }
        }
      }
    },
    "suggest.v1.ListReq": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "suggest.v1.ListResp": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}
`)
}
