// Code generated by tron v0.8.0. DO NOT EDIT.
package config

const (
	ClickhouseDatabase     = "clickhouse_database"
	ClickhousePassword     = "clickhouse_password"
	ClickhouseReadTimeout  = "clickhouse_read_timeout"
	ClickhouseUri          = "clickhouse_uri"
	ClickhouseUser         = "clickhouse_user"
	ClickhouseWriteTimeout = "clickhouse_write_timeout"
	FrontendPath           = "frontend_path"
	ServiceTlsCert         = "service_tls_cert"
	ServiceTlsKey          = "service_tls_key"
)
