// Code generated by tron. You must modify it.

package entry

import (
	"context"

	transport "github.com/loghole/tron/transport"

	"github.com/loghole/dashboard/internal/app/domain"
	"github.com/loghole/dashboard/internal/app/usecases"
	entryV1 "github.com/loghole/dashboard/pkg/entry/v1"
)

type ListEntry interface {
	Do(ctx context.Context, input *usecases.ListEntryIn) ([]*domain.Entry, error)
}

type Implementation struct {
	entryV1.UnimplementedEntryServer
	listEntry ListEntry
}

func NewImplementation(listEntry ListEntry) *Implementation {
	return &Implementation{listEntry: listEntry}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return entryV1.NewEntryServiceDesc(i)
}
